site_name: wagtail-blocks
site_description: A Collection of awesome Wagtail CMS stream-field blocks.
repo_url: https://github.com/ibrahimawadhamid/wagtail_blocks

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - python

pages:
  - Home: 'index.md'
  - Installation: 'installation.md'
  - Usage: 'usage.md'
  - Showcase:
    - 'Standard Blocks': 'showcase/standard-blocks.md'
    - 'Chart': 'showcase/chart.md'
    - 'Map': 'showcase/map.md'